cache_dir: ./data/


comm:
  material: 收集材料#
  show_material: 查看材料#

setting:
  # ------------ 原神公告设置 ------------
  # 屏蔽id
  ann_block:
    - 762
    - 422
    - 423
    - 1263
    - 495
    - 1957
    - 2522
    - 2388
    - 2516
    - 2476
  # 是否开启原神公告推送
  ann_cron_enable: true
  # 是否只允许非群员开启
  ann_enable_only_admin: true
  # 是否默认开启
  ann_group_default_enable: false
  # 刷新获取时间 单位分钟
  ann_cron_time: 20
  # ------------ 查询玩家UID使用的cookie列表 ------------
  #必须设置才能使用 可以登录米游社 获取cookie 主要内容为 account_id=******; cookie_token=*********;
  # javascript:(()=>{_=(n)=>{for(i in(r=document.cookie.split(";"))){var arr=r[i].split("=");if(arr[0].trim()==n)return arr[1];}};c=_("cookie_token")||alert('请重新登录');m=`account_id=${_("account_id")}; cookie_token=${c};`;c&&confirm('确定复制到剪切板?:'+m)&&copy(m)})();
  # 油猴脚本 https://greasyfork.org/scripts/435553-%E7%B1%B3%E6%B8%B8%E7%A4%BEcookie/code/%E7%B1%B3%E6%B8%B8%E7%A4%BEcookie.user.js

  cookies:
    - account_id=000000000; cookie_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
    - account_id=000000000; cookie_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;
    - account_id=000000000; cookie_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx;

    
  # ----------------------------------------------------
  baidu_ocr:
    API_KEY: xxxxxxxxxxxxxxxxx
    SECRET_KEY: xxxxxxxxxxxxxxxxxxxxx